package com.luv2code.springboot.cruddemo.security;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;

/**
 * Security Configuration class for the CRUD demo application.
 *
 * This class defines the security settings using Spring Security's
 * in-memory user details manager. It configures custom users with specific roles
 * to demonstrate role-based access control.
 *
 * Key Features:
 * 1. **In-Memory User Details**:
 *    - Users are defined in-memory for simplicity during development.
 *    - Each user has a username, password, and one or more roles.
 *    - Passwords are prefixed with `{noop}` to indicate that no encoding is applied
 *      (not recommended for production; use password encoding instead).
 *
 * 2. **Impact on Default Security**:
 *    - By defining custom users here, the default username (`user`) and password
 *      generated by Spring Security or those specified in `application.properties`
 *      will no longer work. This is because Spring Security prioritizes beans like
 *      `InMemoryUserDetailsManager` for authentication.
 */
@Configuration
public class DemoSecurityConfig {

    /**
     * Configures an in-memory user details manager with predefined users.
     *
     * @return InMemoryUserDetailsManager containing user details.
     */
    @Bean
    public InMemoryUserDetailsManager userDetailsManager() {

        // User with an Employee role
        UserDetails john = User.builder()
                .username("john")
                .password("{noop}test123") // Password with no encoding
                .roles("Employee")
                .build();

        // User with Employee and Manager roles
        UserDetails mary = User.builder()
                .username("mary")
                .password("{noop}test123") // Password with no encoding
                .roles("Employee", "Manager")
                .build();

        // User with Employee, Manager, and Admin roles
        UserDetails susan = User.builder()
                .username("susan")
                .password("{noop}test123") // Password with no encoding
                .roles("Employee", "Manager", "Admin")
                .build();

        // Return the in-memory user details manager with the defined users
        return new InMemoryUserDetailsManager(john, mary, susan);
    }
}
